region_detector_node:
  ros__parameters:
    # 三区域多边形（map坐标系），格式：[x1, y1, x2, y2, x3, y3, ...]
    battle_region_frame: map
    # self_base_region: [-7.0, -4.0, -7.0, 4.0, -0.5, 4.0, -0.5, -4.0]
    # central_highland_region: [-0.5, -4.0, -0.5, 4.0, 1.5, 4.0, 1.5, -4.0]
    # enemy_base_region: [1.5, -4.0, 1.5, 4.0, 5.0, 4.0, 5.0, -4.0]

    lookahead_distance: 3.0
    publish_rate: 20.0
    plan_topic: /plan
    chase_goal_topic: /chase_goal_pose
    chase_plan_goal_tolerance: 0.75
    # fluctuate_region_1: [5.05, 4.6, 4.25, 4.6, 4.25, 6.2, 5.05, 6.2]
    fluctuate_region_1_yaw: 0.0
    # fluctuate_region_2: [1.5, -6.35, -1.0, -6.35, -1.0, -5.55, 1.5, -5.55]
    fluctuate_region_2: [-2.4, -6.18, -3.49, -5.91, -3.29, -5.16, -2.2, -5.45]
    fluctuate_region_2_yaw: 0.0
    # fluctuate_region_3: [-5.05, -4.6, -4.25, -4.6, -4.25, -6.2, -5.05, -6.2]
    fluctuate_region_3_yaw: 0.0
    # fluctuate_region_4: [-1.5, 6.35, 1.0, 6.35, 1.0, 5.55, -1.5, 5.55]
    fluctuate_region_4: [-1.08, -5.05, -1.81, -4.86, -0.919, -1.51, -0.16, -1.62]
    fluctuate_region_4_yaw: 0.0